{
  "hash": "fa30cbbd3dfc653a706515a9b4a7c201",
  "result": {
    "engine": "knitr",
    "markdown": "---\nfilters:\n  - line-highlight\nexecute: \n  freeze: auto\nfig-width: 5\nfig-asp: 0.75\n---\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n# Case studies {#sec-case-studies}\n\n## Mapping stunting and underwieght risk in Ghana\n\nMalnutrition remains a critical public health issue in many low- and middle-income countries, particularly affecting children under five years of age. It can have long-term consequences on physical growth, cognitive development, and susceptibility to disease. Monitoring childhood nutritional status is essential for evaluating the effectiveness of health interventions and informing policy decisions.\n\nTwo widely used anthropometric indicators derived from child growth measurements are:\n\n- Height-for-Age Z-score (HAZ): A measure of stunting, which reflects chronic malnutrition. Children with a HAZ below -2 standard deviations from the WHO growth reference median are considered stunted, indicating long-term nutritional deprivation or repeated infections.\n\n- Weight-for-Age Z-score (WAZ): A composite indicator of underweight, capturing both acute and chronic malnutrition. Children with WAZ below -2 are considered underweight. This measure is commonly used in population-based surveys because it is relatively easy to collect and interpret.\n\nThese Z-scores are calculated by comparing individual anthropometric measurements to the WHO Child Growth Standards, which were developed based on data from healthy children under optimal environmental and nutritional conditions [@who2006].\n\nGeostatistical models applied to HAZ and WAZ, or to the prevalence of stunting and underweight derived from these scores, can help answer critical questions such as: *Where is the burden of malnutrition highest? How does it relate to socioeconomic or environmental factors? And which areas should be prioritized for targeted nutritional interventions?*\n\nIn this case study, we analyse HAZ and WAZ as continuous outcomes to assess the spatial variation in child malnutrition across Ghana and its association with socioeconomic and demographic covariates.\n\n### Exploratory analysis\n\nWe begin by loading the necessary R packages and the `malnutrition` dataset. This geostatistical dataset is derived from the 2014 Ghana Demographic and Health Survey (DHS) [@ghanaDHS2014], which provides nationally representative data on child health and nutrition. The dataset includes anthropometric measurements, household characteristics, and georeferenced sampling cluster coordinates, making it suitable for spatial analysis of child malnutrition.\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load packages\nlibrary(RiskMap)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(patchwork)\n\n# Load the data\ndata(malnutrition)\n```\n:::\n\n\n\n\n\n\n\n\nThe explanatory variables considered in this analysis are `age` and `wealth`. Figure @fig-maln-expl displays scatterplots of the two nutritional outcomes (`HAZ` and `WAZ`) against age, alongside boxplots stratified by the three levels of the `wealth` variable.\n\nTo explore the relationship between age and nutritional status, the code below applies locally estimated scatterplot smoothing (LOESS) to highlight potential non-linear trends. In addition, we fit linear splines using the function `pmax()` to model a change in slope at specified knots—2 months for HAZ and 1 month for WAZ. These change points were selected heuristically based on visual inspection of the LOESS curves.\n\nAs shown in Figure @fig-maln-expl, the linear splines (green dashed lines) closely follow the LOESS fits (solid red lines), indicating that the piecewise linear models provide an adequate approximation of the age-nutrition relationship.\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter complete cases for relevant variables\nmal <- malnutrition %>%\n  filter(!is.na(HAZ), !is.na(WAZ), !is.na(age), !is.na(wealth))\n\n# Fit spline model for HAZ with knot at 2 months\nmod_haz <- lm(HAZ ~ age + pmax(age - 2, 0), data = mal)\n\n# Fit spline model for WAZ with knot at 1 month\nmod_waz <- lm(WAZ ~ age + pmax(age - 1, 0), data = mal)\n\n# Prediction grid for HAZ\nnewdat_haz <- data.frame(age = seq(min(mal$age), max(mal$age), length.out = 200)) \nnewdat_haz$fit <- predict(mod_haz, newdata = newdat_haz)\n\n# Prediction grid for WAZ\nnewdat_waz <- data.frame(age = seq(min(mal$age), max(mal$age), length.out = 200)) \nnewdat_waz$fit <- predict(mod_waz, newdata = newdat_waz)\n\n# Plot HAZ vs Age\np1 <- ggplot(mal, aes(x = age, y = HAZ)) +\n  geom_point(alpha = 0.3) +\n  geom_smooth(method = \"loess\", colour = \"red\", se = FALSE) +\n  geom_line(data = newdat_haz, aes(x = age, y = fit), \n            colour = \"green\", linetype = \"dashed\", linewidth = 1.2) +\n  labs(title = \"HAZ vs Age\", x = \"Age (months)\", y = \"HAZ\") +\n  theme_minimal()\n\n# Plot WAZ vs Age\np2 <- ggplot(mal, aes(x = age, y = WAZ)) +\n  geom_point(alpha = 0.3) +\n  geom_smooth(method = \"loess\", colour = \"red\", se = FALSE) +\n  geom_line(data = newdat_waz, aes(x = age, y = fit), \n            colour = \"green\", linetype = \"dashed\", linewidth = 1.2) +\n  labs(title = \"WAZ vs Age\", x = \"Age (months)\", y = \"WAZ\") +\n  theme_minimal()\n\n# Boxplots for HAZ and WAZ by wealth\np3 <- ggplot(mal, aes(x = factor(wealth), y = HAZ)) +\n  geom_boxplot(fill = \"lightblue\") +\n  labs(title = \"HAZ by Wealth Group\", x = \"Wealth (1 = Poor, 3 = Rich)\", y = \"HAZ\") +\n  theme_minimal()\n\np4 <- ggplot(mal, aes(x = factor(wealth), y = WAZ)) +\n  geom_boxplot(fill = \"lightgreen\") +\n  labs(title = \"WAZ by Wealth Group\", x = \"Wealth (1 = Poor, 3 = Rich)\", y = \"WAZ\") +\n  theme_minimal()\n\n# Combine plots\n(p1 | p2) / (p3 | p4)\n```\n\n::: {.cell-output-display}\n![Exploratory analysis of HAZ and WAZ by age and wealth. The red lines correspond to LOESS smoothed curves and the green lines to linear splines with change points at 2 months (HAZ) and 1 month (WAZ) of age. Boxplots show variation by household wealth group.](05_case-studies_files/figure-html/fig-maln-expl-1.png){#fig-maln-expl}\n:::\n:::\n\n\n\n\n\n\n\n\nWe begin by fitting a non-spatial model to assess whether there is residual spatial correlation that remains after accounting for the effects of age and wealth. Let $Y_{ij}$ represent either the HAZ or WAZ score for the $j$-th child in the $i$-th cluster. The model takes the following form:\n\n$$\nY_{ij} = \\beta_0 + \\beta_1 a_{ij} + \\beta_2 \\max\\{a_{ij} - c, 0\\} + \\beta_3 w_i + Z_i + U_{ij},\n$$ {#eq-model-haz-waz}\n\nwhere $a_{ij}$ denotes the age in months of child $j$ in cluster $i$, and $w_i$ is the wealth score associated with cluster $i$; as previously stated, the change point $c$ of the linear spline is set to 2 months for HAZ and 1 month for WAZ. The term $Z_i$ is a Gaussian random effect with mean zero and variance $\\tau^2$, capturing between-cluster variation not explained by the covariates. The error term $U_{ij}$ represents child-specific residual variation and is assumed to be Gaussian with mean zero and variance $\\omega^2$.\n\nTo fit this model, we create a cluster ID variable based on the sampling coordinates and include it as a random intercept in the `lmer` function to incorporate the term $Z_i$.\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create ID for the location\nmalnutrition <- malnutrition %>%\n  group_by(lng, lat) %>%\n  mutate(loc_id = cur_group_id()) %>%\n  ungroup()\n```\n:::\n\n\n\n\n\n\n\n\nWe then fit the models using the `lmer` function.\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4)\nhaz_lmer <- \nlmer(HAZ ~ age + pmax(age - 2, 0) + wealth + (1 | loc_id), data = malnutrition)\n\nsummary(haz_lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: HAZ ~ age + pmax(age - 2, 0) + wealth + (1 | loc_id)\n   Data: malnutrition\n\nREML criterion at convergence: 8593.6\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-4.6407 -0.5992  0.0154  0.6098  5.6443 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n loc_id   (Intercept) 0.06939  0.2634  \n Residual             1.39362  1.1805  \nNumber of obs: 2671, groups:  loc_id, 410\n\nFixed effects:\n                 Estimate Std. Error t value\n(Intercept)      -0.39571    0.08170  -4.844\nage              -0.77185    0.04471 -17.265\npmax(age - 2, 0)  0.88486    0.06698  13.211\nwealth            0.38630    0.03611  10.699\n\nCorrelation of Fixed Effects:\n            (Intr) age    p(-2,0\nage         -0.654              \npmax(g-2,0)  0.521 -0.932       \nwealth      -0.616 -0.034  0.038\n```\n\n\n:::\n\n```{.r .cell-code}\nwaz_lmer <- \n  lmer(WAZ ~ age + pmax(age - 1, 0) + wealth + (1 | loc_id), data = malnutrition)\nsummary(waz_lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: WAZ ~ age + pmax(age - 1, 0) + wealth + (1 | loc_id)\n   Data: malnutrition\n\nREML criterion at convergence: 7997.3\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-6.5967 -0.5816  0.0098  0.6312  5.7860 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n loc_id   (Intercept) 0.05625  0.2372  \n Residual             1.11823  1.0575  \nNumber of obs: 2668, groups:  loc_id, 410\n\nFixed effects:\n                 Estimate Std. Error t value\n(Intercept)      -0.50444    0.08951  -5.636\nage              -0.72230    0.09615  -7.512\npmax(age - 1, 0)  0.73510    0.10754   6.835\nwealth            0.27359    0.03238   8.450\n\nCorrelation of Fixed Effects:\n            (Intr) age    p(-1,0\nage         -0.765              \npmax(g-1,0)  0.716 -0.989       \nwealth      -0.494 -0.036  0.037\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\nOf particular interest in the summary of the fitted models above are the estimates of the variances associated with the random effects: $\\tau^2$ for the cluster-level terms $Z_i$, and $\\omega^2$ for the child-specific residuals $U_{ij}$. The estimates suggest that $\\omega^2$ is more than twenty times larger than $\\tau^2$, indicating that the majority of the unexplained variation occurs at the individual child level rather than between clusters. This has important implications for interpretation: any subsequent mapping of the prevalence of stunting or underweight should acknowledge the high degree of within-cluster variability as a limitation. In particular, predictions at unsampled locations may be subject to substantial uncertainty driven by this fine-scale heterogeneity.\n\n\n### Assessing residual spatial correlation and model fitting\n\nWe next explore the residual spatial correlation through the empirical variogram. Hence, we extract the estimate of the random effects from @eq-model-haz-waz and input these into the `s_variogram` function that generates the empirical variogram.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract random effects for HAZ and WAZ and combine them\nre <- data.frame(\n  loc_id = as.numeric(rownames(ranef(haz_lmer)$loc_id)),\n  Z_hat_haz = ranef(haz_lmer)$loc_id[,1],\n  Z_hat_waz = ranef(waz_lmer)$loc_id[,1]\n)\n\n# Extract one row per location with coordinates\nloc_coords <- malnutrition %>%\n  select(loc_id, lng, lat) %>%\n  distinct()\n\n# Merge coordinates into random effects\nre <- left_join(re, loc_coords, by = \"loc_id\")\n\n# Convert to sf and transform into UTM\nlibrary(sf)\nre <- st_as_sf(re, coords = c(\"lng\",\"lat\"), crs = 4326)\nre <- st_transform(re, crs = propose_utm(re))\n\n# Variogram for HAZ\nvar_haz <- s_variogram(re, \"Z_hat_haz\", scale_to_km = TRUE,\n                       n_permutation = 1000)\nvar_waz <- s_variogram(re, \"Z_hat_waz\", scale_to_km = TRUE,\n                       n_permutation = 1000)\nlibrary(patchwork)\n\n# Create ggplot objects\np_haz <- plot_s_variogram(var_haz, plot_envelope = TRUE) + \n  ggtitle(\"HAZ\")\n\np_waz <- plot_s_variogram(var_waz, plot_envelope = TRUE) + \n  ggtitle(\"WAZ\")\n\np_haz + p_waz\n```\n\n::: {.cell-output-display}\n![Empirical variograms for HAZ and WAZ based on the estimated random effects from @eq-model-haz-waz.](05_case-studies_files/figure-html/fig-maln-vari-1.png){#fig-maln-vari}\n:::\n:::\n\n\n\n\n\n\n\n\n@fig-maln-vari shows the variogram for both HAZ and WAZ. In both cases, we observe that is residual spatial correlation in the data that is not explained by either age or the wealth index. We next extend the model in @eq-model-haz-waz to address this issue.\n\nFor our geostatistical analysis of HAZ and WAZ, we consider the following model:\n\n$$\nY_{ij} = \\beta_0 + \\beta_1 a_{ij} + \\beta_2 \\max\\{a_{ij} - c, 0\\} + \\beta_3 w_i + S(x_i) + U_{ij},\n$$ {#eq-model-haz-waz}\n\nwhere $S(x)$ is a zero-mean, stationary, and isotropic Gaussian process with variance $\\sigma^2$ and an exponential correlation function with scale parameter $\\phi$. In this geostatistical extension, we replace the cluster-level random effect $Z_i$ from @eq-model-haz-waz with the spatial process $S(x_i)$. The random effect $Z_i$ was previously used in the Binomial mixed model to account for unexplained variation between clusters. It is also possible to include both $S(x_i)$ and $Z_i$ in the model, so that the total unexplained variation between clusters is decomposed into a spatially structured component, $S(x_i)$, and an unstructured component, $Z_i$. However, this approach is not recommended in the initial model specification, as it may lead to identifiability issues. It can be considered later in the analysis if justified by model diagnostics.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove missing data from the WAZ outcome\nmalnutrition <- malnutrition[complete.cases(malnutrition[,\"WAZ\"]),]\n\n# Converting the data-frame into an sf object\nmalnutrition_sf <- st_as_sf(malnutrition, coords = c(\"lng\", \"lat\"), crs = 4326)\nmalnutrition_sf <- st_transform(malnutrition_sf, crs = propose_utm(malnutrition_sf))\n\n# Maximum likelihood estimation for the HAZ and WAZ outcomes\nhaz_fit <- \nglgpm(HAZ ~ age + pmax(age - 1, 0) + wealth + gp(),\n      data=malnutrition_sf, family = \"gaussian\")\n\nwaz_fit <- \n  glgpm(HAZ ~ age + pmax(age - 1, 0) + wealth + gp(),\n        data=malnutrition_sf, family = \"gaussian\") \n```\n:::\n\n\n\n\n\n\n\nWe then summarize the fit of models.\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(haz_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear geostatsitical model \n'Lower limit' and 'Upper limit' are the limits of the 95% confidence level intervals \n\n Regression coefficients \n                   Estimate Lower limit Upper limit     StdErr  z.value p.value\n(Intercept)      -0.2158950  -0.4338747   0.0020848  0.1112162  -1.9412 0.05223\nage              -1.3073560  -1.4135715  -1.2011404  0.0541926 -24.1243 < 2e-16\npmax(age - 1, 0)  1.2288215   1.1496224   1.3080207  0.0404085  30.4100 < 2e-16\nwealth            0.3520544   0.3319696   0.3721393  0.0102476  34.3550 < 2e-16\n                    \n(Intercept)      .  \nage              ***\npmax(age - 1, 0) ***\nwealth           ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nOffset included into the linear predictor \n\n                         Estimate Lower limit Upper limit\nMeasuremment error var.   1.4371      1.4254      1.4489\n\n Spatial Guassian process \nMatern covariance parameters (kappa=0.5) \n                      Estimate Lower limit Upper limit\nSpatial process var.  0.069453    0.061423      0.0785\nSpatial corr. scale  36.529380   30.187727     44.2032\nVariance of the nugget effect fixed at 0 \n\n Log-likelihood: -1859.246\n\n AIC: 3718.491\n \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(waz_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear geostatsitical model \n'Lower limit' and 'Upper limit' are the limits of the 95% confidence level intervals \n\n Regression coefficients \n                   Estimate Lower limit Upper limit     StdErr  z.value\n(Intercept)      -0.4580088  -0.6499668  -0.2660509  0.0979395  -4.6764\nage              -0.7295504  -0.8235412  -0.6355596  0.0479554 -15.2131\npmax(age - 1, 0)  0.7421647   0.6720850   0.8122443  0.0357556  20.7566\nwealth            0.2254477   0.2076797   0.2432157  0.0090655  24.8689\n                   p.value    \n(Intercept)      2.919e-06 ***\nage              < 2.2e-16 ***\npmax(age - 1, 0) < 2.2e-16 ***\nwealth           < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nOffset included into the linear predictor \n\n                         Estimate Lower limit Upper limit\nMeasuremment error var.   1.1253      1.1161      1.1346\n\n Spatial Guassian process \nMatern covariance parameters (kappa=0.5) \n                      Estimate Lower limit Upper limit\nSpatial process var.  0.049912    0.043750      0.0569\nSpatial corr. scale  35.836303   28.815346     44.5679\nVariance of the nugget effect fixed at 0 \n\n Log-likelihood: -1530.593\n\n AIC: 3061.187\n \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nThe spatial component of the models reveals a moderate degree of spatial structure in the HAZ and WAZ outcomes. For HAZ, the estimated spatial variance is approximately 0.069, while the individual-level radom effect's variance is substantially larger at around 1.437. For WAZ, the spatial variance is estimated at 0.050, compared to the variance of the individual-level radom effect's variance of 1.125. In both models, as already observed when fitting Binomial mixed models, this indicates that the majority of the residual variation is due to individual-level noise or unstructured heterogeneity rather than spatially structured effects. The relative contribution of the spatial process to the total unexplained variation is therefore relatively small. Nevertheless, geostatistical analysis remains valuable also in this context. Even when spatial effects explain only a modest proportion of the variation, the model still enables spatial prediction of the average spatial pattern for the outcome of interest across the study area. This is useful for identifying areas where child malnutrition is systematically higher or lower, guiding targeted interventions and informing resource allocation. We explore these implications further in the next section on geostatistical prediction for HAZ and WAZ.\n\n### Prediction and assessment of model calibration\n\nStunting and underweight are standard indicators used to assess child malnutrition. A child is defined as \\textit{stunted} if their height-for-age $z$-score (HAZ) is below $-2$ standard deviations from the median of the WHO Child Growth Standards, i.e., HAZ < -2. Similarly, a child is considered \\textit{underweight} if their weight-for-age $z$-score (WAZ) falls below $-2$, i.e., WAZ < -2 [@sdg2201meta2025]. These thresholds are based on the World Health Organization (WHO) growth reference standards, which provide a normative basis for assessing nutritional status in children under five years of age [@who_underweight2024].\n\nWe now define the predictive targets for stunting and underweight prevalence in terms of the adopted geostatistical model. Both indicators correspond to the probability that a child's z-score falls below $-2$, that is, $Y(x) < -2$, where $Y(x)$ denotes either the HAZ or WAZ score at location $x$. Under the model specification, the prevalence is therefore defined as\n\n$$\nT(x) = P\\left\\{ Y(x) < -2 \\,\\middle|\\, S(x) \\right\\} = \\Phi\\left( -\\frac{\\mu + S(x) + 2}{\\omega} \\right),\n$$ {#eq-prev-maln}\n\nwhere $\\Phi(\\cdot)$ is the cumulative distribution function of the standard normal distribution, $\\mu$ is the linear predictor including the effects of covariates at individual- and cluster-level (as defined by the coefficients $\\beta_1$ to $\\beta_3$ of @eq-model-haz-waz) as well as the intercept, and $\\omega^2$ is the variance of the individual-level residual term. In @eq-prev-maln, we condition on $S(x)$ because this allows us to define both stunting an underweight prevalence as a spatially varying predictive target.\n\nTo implement this in `RiskMap`, we begin by generating a predictive grid over the study region. In this case, we use a regular grid with 10 km by 10 km resolution. We then draw predictive samples of the spatial effect $S(x)$ at each grid location, conditional on the observed data. For the `age` variable, we fix it at 2 months for HAZ and 1 month for WAZ, respectively. The `wealth` variable is set to its lowest value of 1. These choices are made to visualize the predictive target for the subgroup of children most at risk of stunting and underweight, as identified through exploratory analysis and the estimated regression coefficients. The code below illustrates this procedure.\n \n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Boundaries of Ghana\nlibrary(rgeoboundaries)\nghana <- geoboundaries(country = \"Ghana\", adm_lvl = \"adm0\")\nghana <- st_transform(ghana, st_crs(malnutrition_sf))\n\nghana_grid <- create_grid(ghana, spat_res = 10)\n\nn_pred <- nrow(st_coordinates(ghana_grid))\n\n# Prediction of S(x) and covariates effects over the grid for\n\n# HAZ\nhaz_pred_grid <- pred_over_grid(haz_fit,\n                                grid_pred = ghana_grid,\n                                predictors = data.frame(\n                                  # Setting age to 2 months\n                                  age = rep(2, n_pred),\n                                  # Setting wealth to 1 (least wealthy)\n                                  wealth = rep(1, n_pred)\n                                ))\n# WAZ\nwaz_pred_grid <- pred_over_grid(waz_fit,\n                                grid_pred = ghana_grid,\n                                predictors = data.frame(\n                                  # Setting age to 1 month\n                                  age = rep(1, n_pred),\n                                  # Setting wealth to 1 (least wealthy)\n                                  wealth = rep(1, n_pred)\n                                ))\n```\n:::\n\n\n\n\n\n\n\n\nWe then use the `pred_target_grid` function to generate predictive summaries of stunting and underweight prevalence, as defined in @eq-prev-maln. To quantify uncertainty in the predictions, we report the coefficient of variation, which provides a standardized measure of relative uncertainty across the prediction grid.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prediction of stunting prevalence\nsd_ind_haz <- sqrt(coef(haz_fit)$sigma2_me)\nstunting_prev <-\npred_target_grid(haz_pred_grid,\n                 f_target = list(prev = function(x) pnorm((-2-x)/sd_ind_haz)),\n                 pd_summary = list(mean = mean,\n                                       cv = function(x) sd(x)/mean(x)))\n\n# Prediction of underweight prevalence\nsd_ind_waz <- sqrt(coef(waz_fit)$sigma2_me)\nunderw_prev <-\n  pred_target_grid(waz_pred_grid,\n                   f_target = list(prev = function(x) pnorm((-2-x)/sd_ind_waz)),\n                   pd_summary = list(mean = mean,\n                                     cv = function(x) sd(x)/mean(x)))\n```\n:::\n\n\n\n\n\n\n\n\nFinally, we visualize the results in the map shown in @fig-maln-pred. The maps reveal a clear hotspot for both stunting and underweight, with predicted prevalence values reaching approximately $45\\%$ and $24\\%$, respectively. Notably, this same region also exhibits lower predictive uncertaint, measured by the coefficient of variation, compared to other areas in Ghana.\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set up a 2x2 layout\nlayout(matrix(1:4, nrow = 2, byrow = TRUE))\npar(mar = c(4, 4, 4, 5))  # Adjust margins\n\n# Top row: stunting\nplot(stunting_prev, which_target = \"prev\", which_summary = \"mean\",\n     main = \"Stunting: Predictive Mean\")\nplot(stunting_prev, which_target = \"prev\", which_summary = \"cv\",\n     main = \"Stunting: Coefficient of Variation\")\n\n# Bottom row: underweight\nplot(underw_prev, which_target = \"prev\", which_summary = \"mean\",\n     main = \"Underweight: Predictive Mean\")\nplot(underw_prev, which_target = \"prev\", which_summary = \"cv\",\n     main = \"Underweight: Coefficient of Variation\")\n```\n\n::: {.cell-output-display}\n![Predictive mean and coefficient of variation for stunting and underweight prevalence estimates. The top row shows predictions for stunting, while the bottom row corresponds to underweight. For each indicator, the left panel shows the predictive mean and the right panel the coefficient of variation.](05_case-studies_files/figure-html/fig-maln-pred-1.png){#fig-maln-pred}\n:::\n:::\n\n\n\n\n\n\n\n\n\nTo assess the predictive performance and calibration of our geostatistical models for HAZ and WAZ, we perform a cross-validation exercise using the `assess_pp` function. Cross-validation is conducted by repeatedly splitting the data into training and testing sets, ensuring that prediction locations are at least 5 km away from the nearest training point. Specifically, we set `n_size = 100` prediction locations for the test set, impose a minimum distance constraint of 5 km (`min_dist = 5`), and repeat the process over 10 test sets randomly drawn under those conditions (`iter = 10`) using `method=\"regularized\"` as the sampling method. \n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# HAZ\nassess_haz <-\nassess_pp(list(HAZ = haz_fit),\n          n_size = 100,\n          min_dist = 5,\n          iter = 10,\n          method = \"regularized\")\n\n# WAZ\nassess_waz <-\n  assess_pp(list(WAZ = waz_fit),\n            n_size = 100,\n            min_dist = 5,\n            iter = 10,\n            method = \"regularized\")\n```\n:::\n\n\n\n\n\n\n\nWe note that for a Gaussian linear geostatistical model, the `assess_pp` function does not compute the average non-randomized probability integral transform (AnPIT, introduced in @sec-anpit), as this measure is specifically designed for count outcomes. Instead, it employs the standard probability integral transform (PIT), defined as $\\text{PIT}(y) = F_{M}(y)$, where $F_{M}(y)$ is the cumulative distribution function of the predictive distribution evaluated at the observed value $y$. The PIT transforms the observed outcomes in the test set such that, if the model is well-calibrated, these transformed values should follow a uniform distribution. Deviations from uniformity indicate potential issues with calibration and predictive accuracy.\n\n@fig-maln-pit shows the results of the cross-validation exercise visualized through PIT curves for HAZ and WAZ. Similarly to the way we have interpreted the AnPIT curves, the PIT curves indicate good calibration when they lie close to the identity line, meaning the predictive distributions accurately reflect the observed variability in the test sets. The results shown in @fig-maln-pit demonstrate that, for all ten test sets and for both HAZ and WAZ, the PIT curves closely align with the identity line, confirming that the models are well-calibrated and provide reliable uncertainty quantification.\n\n\n\n\n\n\n\n\n::: {#fig-maln-pit .cell}\n\n```{.r .cell-code}\n# Generate PIT plots\np_haz <- plot_AnPIT(assess_haz, mode = \"all\")\np_waz <- plot_AnPIT(assess_waz, mode = \"all\")\n\n# Arrange side-by-side\nlibrary(gridExtra)\ngrid.arrange(p_haz, p_waz, ncol = 2)\n```\n\n::: {.cell-output-display}\n![PIT: HAZ](05_case-studies_files/figure-html/fig-maln-pit-1.png){#fig-maln-pit}\n:::\n\nAssessment of the models calibration. The left panel shows the probability integral transform (PIT) curve for HAZ, and the right panel for WAZ. In both panels, the red dahsed line corresponds to the identity line.\n:::\n\n\n\n\n\n\n\n\n### Summary and conclusions\n\nThis case study demonstrated the utility of geostatistical modeling for mapping child malnutrition in Ghana using continuous anthropometric measurements, namely HAZ and WAZ Z-scores. By modeling these outcomes directly, we were able to define stunting and underweight prevalence as predictive probabilities based on threshold exceedance (e.g., HAZ < -2), rather than by dichotomizing the data prior to analysis. This approach allowed us to retain the full information content of the measurements and to produce spatially resolved predictions of prevalence along with associated uncertainty estimates. Readers interested in a more in-depth treatment of this modeling strategy are referred to @kyomuhangi2021, which discusses the loss of information and degradation in predictive performance that can result from dichotomizing continuous outcomes in geostatistical settings.\n\nMore broadly, this case study illustrated how geostatistical models can be used to analyze individual-level outcomes while accounting for both child-level and household-level covariates. Aggregation of data across individuals, such as using average HAZ or WAZ scores per location, is not required and can in fact introduce several complications. In particular, the number of children per cluster varies, which implies that an analysis based on cluster-level averages would require a heteroscedastic specification for the residual term to appropriately reflect varying precision across locations. Ignoring this could lead to unreliable predictive inferences.\n\nIn conclusion, this analysis showed that neither dichotomization nor aggregation is necessary in geostaistical analysis. Instead, geostatistical models should be fitted to individual-level continuous outcomes, and suitable predictive targets and summaries of uncertainty can then be derived from the fitted model.\n\n## Mapping river blindness in Malawi\n\n## Mapping mosquitoes abundance in Cameroon\n",
    "supporting": [
      "05_case-studies_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}