project:
  type: book

book:
  title: "Model-based geostatistics for global public health using R"
  author:
    - Emanuele Giorgi
    - Claudio Fronterre
  date: "03/03/2023"
  search: true
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_handling-spatial-data.qmd
    - 03_model-fitting.qmd
    - 04_model-validation.qmd
    - 05_geostatistical-prediction.qmd
    - 06_case-studies.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: paged
  pdf:
    documentclass: krantz
    keep-tex: true
    include-in-header: preamble.tex

execute: 
  cache: false

editor: visual

